const Strings = {
  Welcome: 'Welcome to ',
  InstaMart: 'InstaMart!!',
  Title: 'InstaMart',
  Tagline: "Find the best items around you at lowest price.",
  Description:
    'Lorem ipsum dolor sit amet. Et commodi enim ut modi maxime quo minus rerum a nihil commodi et aspernatur officiis et repudiandae alias. Quo aperiam consequatur',
  SignUp: 'Sign up',
  Login: 'Log In',
  Error1: 'Please fill all details',
  Title1: "Let's get Started",
  Title2: 'Already Have an account?',
  Name: 'Name',
  Email: 'Email',
  Mob: 'Contact Number',
  Password: 'Password',
  CPassword: 'Confirm Password',
  Success: 'Success',
  Cancel: 'Cancel',
  Alertt: 'Are you sure you want to remove all items ?',
  LogoutTxt: 'Do you want to LogOut',
  CtnShp: 'Continue Shopping',
  FontFamily: 'Itim-Regular',
};
export default Strings;